CREATE TABLE item_to_category (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_id INTEGER,
    category_id INTEGER,
    user_id INTEGER,
    FOREIGN KEY (item_id) REFERENCES items(id),
    FOREIGN KEY (category_id) REFERENCES categories(id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);