CREATE TABLE pantry (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    user_id INTEGER NOT NULL,
    category_1 category NOT NULL,
    category_2 category,
    category_3 category,
    category_4 category,
    category_5 category,
    category_6 category,
    category_7 category,
    quantity INTEGER NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id)
);