INSERT INTO items (item_name, user_id, category_1, category_2, category_3, category_4, category_5, category_6, category_7)
VALUES
    ('Chicken Sandwich', 1, 'protein', null, null, null, null, null, null),
    ('Lunchable: Turkey Sandwich', 1, 'protein', 'carb', 'combo', null, null, null, null),
    ('Spaghetti with Meatballs', 1, 'protein', 'carb', 'combo', null, null, null, null),
    ('Mashed Potatoes', 1, 'carb', null, null, null, null, null, null),
    ('Corn', 1, 'vegetable', null, null, null, null, null, null),
    ('Peas', 1, 'vegetable', null, null, null, null, null, null),
    ('Green Beans', 1, 'vegetable', null, null, null, null, null, null),
    ('Apple Slices', 1, 'fruit', null, null, null, null, null, null),
    ('Grapes', 1, 'fruit', null, null, null, null, null, null),
    ('Watermelon', 1, 'fruit', null, null, null, null, null, null),
    ('Milk', 1, 'drink', null, null, null, null, null, null),
    ('Chocolate Milk', 1, 'drink', null, null, null, null, null, null),
    ('Juice', 1, 'drink', null, null, null, null, null, null),
    ('Brownie', 1, 'dessert', null, null, null, null, null, null),
    ('Brownie', 1, 'dessert', 'carb', 'vegetable', 'fruit', 'drink', 'protein', 'combo'),
    ('Little Bites Muffins', 1, 'dessert', 'carb', 'combo', null, null, null, null),
    ('Applesauce', 1, 'fruit', null, null, null, null, null, null),
    ('Banana', 1, 'fruit', null, null, null, null, null, null),
    ('Chicken Pita Pocket', 1, 'carb', 'protein', 'combo', null, null, null, null),
    ('Chips', 1, 'carb', null, null, null, null, null, null),
    ('Protein Shake', 1, 'protein', 'drink', 'combo', null, null, null, null),
    ('Oranges', 1, 'fruit', null, null, null, null, null, null);